[package]
description = "Ethcore client."
name = "parity"
version = "0.9.0"
license = "GPL-3.0"
authors = ["Ethcore <admin@ethcore.io>"]

[dependencies]
log = "0.3"
env_logger = "0.3"
rustc-serialize = "0.3"
docopt = "0.6"
docopt_macros = "0.6"
ctrlc = { git = "https://github.com/tomusdrw/rust-ctrlc.git" }
clippy = "0.0.41"
ethcore-util = { path = "util" }
ethcore = { path = "ethcore" }
ethsync = { path = "sync" }
ethcore-rpc = { path = "rpc", optional = true }
fdlimit = { path = "util/fdlimit" }
target_info = "0.1"

[features]
default = ["rpc"]
rpc = ["ethcore-rpc"]

[[bin]]
path = "parity/main.rs"
name = "parity"
