[package]
description = "Ethcore library"
homepage = "http://ethcore.io"
license = "GPL-3.0"
name = "ethcore"
version = "0.1.0"
authors = ["Ethcore <admin@ethcore.io>"]

[dependencies]
log = "0.3"
env_logger = "0.3"
ethcore-util = { path = "util" }
rustc-serialize = "0.3"
flate2 = "0.2"
rocksdb = "0.3"
heapsize = "0.2.0"
rust-crypto = "0.2.34"
time = "0.1"
#interpolate_idents = { git = "https://github.com/SkylerLipthay/interpolate_idents" }
evmjit = { path = "rust-evmjit", optional = true }
ethash = { path = "ethash" }
num_cpus = "0.2"
clippy = "0.0.37"
docopt = "0.6"
ctrlc = "1.0"
jsonrpc-core = { version = "1.0", optional = true }
jsonrpc-http-server = { version = "1.0", optional = true }

[features]
jit = ["evmjit"]
evm_debug = []
test-heavy = []
rpc = ["jsonrpc-core", "jsonrpc-http-server"]

[[bin]]
name = "client"
path = "src/bin/client/main.rs"
