[package]
description = "Ethcore jsonrpc"
name = "ethcore-rpc"
version = "0.9.99"
license = "GPL-3.0"
authors = ["Ethcore <admin@ethcore.io"]

[lib]

[dependencies]
serde = "0.6.7"
serde_macros = "0.6.13"
serde_json = "0.6.0"
jsonrpc-core = "1.1.2"
jsonrpc-http-server = "1.1.2"
ethcore-util = { path = "../util" }
ethcore = { path = "../ethcore" }
ethsync = { path = "../sync" }
clippy = { version = "0.0.41", optional = true }
target_info = "0.1.0"
rustc-serialize = "0.3"

[features]
default = []
dev = ["clippy", "ethcore/dev", "ethcore-util/dev", "ethsync/dev"]
