[package]
description = "Ethcore jsonrpc"
name = "ethcore-rpc"
version = "0.9.0"
license = "GPL-3.0"
authors = ["Ethcore <admin@ethcore.io"]

[lib]

[dependencies]
serde = "0.6.7"
serde_macros = { git = "https://github.com/debris/serde", path = "serde_macros" }
serde_json = "0.6.0"
jsonrpc-core = { git = "https://github.com/debris/jsonrpc-core" }
jsonrpc-http-server = { git = "https://github.com/debris/jsonrpc-http-server" }
ethcore-util = { path = "../util" }
ethcore = { path = "../ethcore" }
ethsync = { path = "../sync" }
clippy = "0.0.41"
target_info = "0.1.0"
rustc-serialize = "0.3"
