[package]
description = "Ethcore blockchain sync"
name = "ethsync"
version = "0.9.99"
license = "GPL-3.0"
authors = ["Ethcore <admin@ethcore.io"]

[lib]

[dependencies]
ethcore-util = { path = "../util" }
ethcore = { path = ".." }
clippy = { version = "0.0.44", optional = true }
log = "0.3"
env_logger = "0.3"
time = "0.1.34"
rand = "0.3.13"

[features]
default = []
dev = ["clippy", "ethcore/dev", "ethcore-util/dev"]
