[package]
description = "Ethcore Trusted Signer"
homepage = "http://ethcore.io"
license = "GPL-3.0"
name = "ethcore-signer"
version = "1.2.0"
authors = ["Ethcore <admin@ethcore.io>"]
build = "build.rs"

[build-dependencies]
rustc_version = "0.1"
serde_codegen = { version = "0.7.0", optional = true }
syntex = "^0.32.0"

[dependencies]
serde = "0.7.0"
serde_json = "0.7.0"
rustc-serialize = "0.3"
ethcore-util = { path = "../util" }
log = "0.3"
env_logger = "0.3"
ws = "0.4.7"

serde_macros = { version = "0.7.0", optional = true }
clippy = { version = "0.0.69", optional = true}

[features]
default = ["serde_codegen"]
nightly = ["serde_macros"]
dev = ["clippy"]
